# Generated by Django 5.1.7 on 2025-03-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('irrigation', '0001_initial'),
        ('sensors', '0002_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField(help_text='AI-generated irrigation advice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('irrigation_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='irrigation.irrigationzone')),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='sensors.sensordata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
